// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKzC3wysL16xR1WHAanNAIc4Jk2D7WeIw',
    appId: '1:584323874407:web:51d829756adc9a641e9ec2',
    messagingSenderId: '584323874407',
    projectId: 'pawfect-815d4',
    authDomain: 'pawfect-815d4.firebaseapp.com',
    storageBucket: 'pawfect-815d4.firebasestorage.app',
    measurementId: 'G-T5DHLZZ3VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs2QadOu8V5bMewEdLiiHTRBCbWnr8QoA',
    appId: '1:584323874407:android:efc6c59abf5e1f641e9ec2',
    messagingSenderId: '584323874407',
    projectId: 'pawfect-815d4',
    storageBucket: 'pawfect-815d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCENsVl2Oxz0GKCTL5VObZjXfP6JVHhvnE',
    appId: '1:584323874407:ios:0969ffe51f0e32d51e9ec2',
    messagingSenderId: '584323874407',
    projectId: 'pawfect-815d4',
    storageBucket: 'pawfect-815d4.firebasestorage.app',
    iosBundleId: 'com.example.pawfect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCENsVl2Oxz0GKCTL5VObZjXfP6JVHhvnE',
    appId: '1:584323874407:ios:0969ffe51f0e32d51e9ec2',
    messagingSenderId: '584323874407',
    projectId: 'pawfect-815d4',
    storageBucket: 'pawfect-815d4.firebasestorage.app',
    iosBundleId: 'com.example.pawfect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKzC3wysL16xR1WHAanNAIc4Jk2D7WeIw',
    appId: '1:584323874407:web:dccae25f3bcc34ef1e9ec2',
    messagingSenderId: '584323874407',
    projectId: 'pawfect-815d4',
    authDomain: 'pawfect-815d4.firebaseapp.com',
    storageBucket: 'pawfect-815d4.firebasestorage.app',
    measurementId: 'G-0BWSYW721P',
  );
}
